package com.gitddo.analysis.contract;

public enum AiErrorCode {
	INVALID_REQUEST,
	UNSUPPORTED_COMBINATION,
	POLICY_VIOLATION,
	LLM_TIMEOUT,
	LLM_RATE_LIMITED,
	LLM_SERVICE_ERROR,
	STRUCTURED_OUTPUT_INVALID,
	INTERNAL_ERROR
}
