package com.gitddo.analysis.domain;

public enum EvidenceKind {
	REPOSITORY_METADATA,
	LANGUAGE_BREAKDOWN,
	README,
	FILE_TREE_SUMMARY,
	BUILD_MANIFEST,
	CI_CONFIGURATION,
	CONTAINER_CONFIGURATION,
	API_DOCUMENTATION,
	PROJECT_STRUCTURE,
	COMMIT_SUMMARY,
	PULL_REQUEST,
	CHANGED_FILES,
	ACTIVITY_SUMMARY
}
