package com.gitddo.analysis.domain;

public enum P0EvidenceKind {
	REPOSITORY_METADATA,
	LANGUAGE_BREAKDOWN,
	README,
	FILE_TREE_SUMMARY,
	BUILD_MANIFEST,
	CI_CONFIGURATION,
	CONTAINER_CONFIGURATION,
	API_DOCUMENTATION,
	PROJECT_STRUCTURE
}
