CREATE TABLE github_repositories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id BIGINT NOT NULL UNIQUE,
    github_user_id BIGINT NOT NULL REFERENCES github_users (id) ON DELETE CASCADE,
    owner_login VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    full_name VARCHAR(512) NOT NULL,
    description TEXT,
    html_url VARCHAR(2048) NOT NULL,
    language VARCHAR(255),
    fork BOOLEAN NOT NULL,
    archived BOOLEAN NOT NULL,
    default_branch VARCHAR(255),
    stargazers_count INTEGER NOT NULL,
    forks_count INTEGER NOT NULL,
    pushed_at TIMESTAMP WITH TIME ZONE,
    github_updated_at TIMESTAMP WITH TIME ZONE,
    synced_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_github_repositories_user ON github_repositories (github_user_id);
CREATE INDEX idx_github_repositories_owner ON github_repositories (LOWER(owner_login));
CREATE INDEX idx_github_repositories_name ON github_repositories (LOWER(name));
