CREATE TABLE github_user_repository_accesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_user_id BIGINT NOT NULL REFERENCES github_users (id) ON DELETE CASCADE,
    repository_id BIGINT NOT NULL REFERENCES github_repositories (id) ON DELETE CASCADE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_github_user_repository_access UNIQUE (github_user_id, repository_id)
);

INSERT INTO github_user_repository_accesses (github_user_id, repository_id)
SELECT github_user_id, id
FROM github_repositories;

DROP INDEX idx_github_repositories_user;
ALTER TABLE github_repositories DROP COLUMN github_user_id;

CREATE INDEX idx_repository_access_user_active
    ON github_user_repository_accesses (github_user_id, active);
CREATE INDEX idx_repository_access_repository
    ON github_user_repository_accesses (repository_id);
