CREATE TABLE portfolios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_user_id BIGINT NOT NULL REFERENCES github_users (id) ON DELETE CASCADE,
    title VARCHAR(120) NOT NULL,
    evaluation_purpose VARCHAR(50) NOT NULL,
    target_level VARCHAR(50),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE portfolio_evaluation_areas (
    portfolio_id BIGINT NOT NULL REFERENCES portfolios (id) ON DELETE CASCADE,
    evaluation_area VARCHAR(50) NOT NULL,
    CONSTRAINT pk_portfolio_evaluation_areas PRIMARY KEY (portfolio_id, evaluation_area)
);

CREATE TABLE portfolio_repositories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL REFERENCES portfolios (id) ON DELETE CASCADE,
    repository_id BIGINT NOT NULL REFERENCES github_repositories (id),
    contribution_description TEXT NOT NULL,
    role_summary TEXT,
    display_order INTEGER NOT NULL,
    CONSTRAINT uk_portfolio_repository UNIQUE (portfolio_id, repository_id)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT uk_portfolio_repository_order UNIQUE (portfolio_id, display_order)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE portfolio_repository_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_repository_id BIGINT NOT NULL
        REFERENCES portfolio_repositories (id) ON DELETE CASCADE,
    role_type VARCHAR(50) NOT NULL,
    participation_level VARCHAR(50) NOT NULL,
    primary_role BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_portfolio_repository_role UNIQUE (portfolio_repository_id, role_type)
);

CREATE UNIQUE INDEX uk_portfolio_repository_primary_role
    ON portfolio_repository_roles (portfolio_repository_id)
    WHERE primary_role = TRUE;

CREATE TABLE evaluation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL REFERENCES portfolios (id) ON DELETE CASCADE,
    sequence INTEGER NOT NULL,
    portfolio_version BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    input_snapshot JSONB NOT NULL,
    result JSONB,
    evaluator_version VARCHAR(100),
    failure_reason TEXT,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_evaluation_run_sequence UNIQUE (portfolio_id, sequence)
);

CREATE INDEX idx_portfolios_user ON portfolios (github_user_id, deleted_at);
CREATE INDEX idx_portfolio_repositories_portfolio ON portfolio_repositories (portfolio_id);
CREATE INDEX idx_evaluation_runs_portfolio ON evaluation_runs (portfolio_id, sequence DESC);
